* Features to Implement
 - [X] Add Booklist feature
   Let the user add, remove and visit a booklist made up of org-mode links which can easily be opened up through helm.
 - [X] Add a function to browse the wiki
 - [X] Create a function to extract subtree(s) into a new wiki article.
 - [X] Implement a way to preset the arguments passed to a code block as it is created.
 - [X] Create functions to insert source code blocks.
 - [X] Create functions to create a new wiki.
 - [X] Implement a function which creates a new article in the current subfolder
 - [X] Implement function to rename entry.
 - [X] Implement a function to open the index of the current wiki.
 - [X] Support exploring multiple wiki roots
   The user should be able to access multiple wiki's with different roots and select which one should be explored.
 - [ ] Add org capture template which is used to update the index when a new article is created.
 - [ ] Support multiple reading lists in different roots
 - [ ] Add org-structure template expansions. Make them be enabled only by the user so they are not loaded in automatically.
 - [ ] Create a hydra 
 - [X] Load code blocks only if the user wants to.(done for speedup)
